name: Publish Sapi Release

on:
  push:
    branches:
      - main
    paths:
      - 'V*/Install/**'
      - 'V*/Documentation/sapi.html'
      - 'docs/index.html'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity
        run: echo "workflow with path filters is valid"
