name: Publish Sapi Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity
        run: echo "workflow is valid"
